# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
#    - !!js/regexp .foundation-mq
#    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/PACE/themes"
    - "bower_components/compass-mixins/lib"
    - "bower_components/groundworkcss/src/sass"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries requried by Groundwork
    - "bower_components/jquery/dist/jquery.min.js"
    - "bower_components/modernizer/modernizr.js"
    # Core Groundwork files
    - "bower_components/groundworkcss/js/groundwork.all.js"
    # Libraries
    - "bower_components/PACE/pace.min.js"
    # My JS files
    - "src/assets/js/!(common).js"
    - "src/assets/js/common.js"
